server:
  port: 8080

spring:
  application:
    name: dynamic-menu
  datasource:
    url: jdbc:mysql://localhost:3306/helloworld?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.web: DEBUG
    org.apache.ibatis: DEBUG
    com.baomidou.mybatisplus.core: DEBUG
    com.baomidou.mybatisplus.extension: DEBUG
    com.zaxxer.hikari: INFO
    net.wcloud.helloworld: DEBUG

app:
  jwt:
    secret: "helloworld-dynamicmenu-secret-1234567890"
    expire-seconds: 86400
    header: Authorization
    token-prefix: "Bearer "
